config/routes.rb
TimOcchipinti::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :contributions, only: [:new, :create, :check]
  resources :blogs, only: [:show, :index]
  resources :news_articles, :only => :index

  resources :sessions, only: [:new, :create, :destroy]
  resources :guests, only: [:new, :create]
  resources :galleries, :has_many => :photos
  resources :photos

  root to:'pages#home'

  match '/about_tim',  	            to: 'pages#about_tim'
  match '/vision',                  to: 'pages#vision'
  match '/contribute',              to: 'contributions#new'
  match '/contribute/check',        to: 'contributions#check'
  match '/media',                   to: 'pages#media'
  match '/mediablog',               to: 'pages#media'
  match '/status_reports',          to: 'pages#status_reports'
  match '/contact',		              to: 'contact_us/contacts#new'
  match '/admin',                   to: 'pages#admin'
  match '/signin',                  to: 'sessions#new'
  match '/signout',                 to: 'sessions#destroy', via: :delete




end

app/models/blog.rb
class Blog < ActiveRecord::Base
  attr_accessible :content, :date, :tagline, :title, :image, :remote_image_url
  mount_uploader :image, ImageUploader

  validates :title, presence: true
  validates :content, presence: true
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
	 def index
    	@archive_news = NewsArticle.all(:order => "date DESC")
        @blogs = Blog.find(:all, :order => "created_at DESC")  
    end

	def show
		@full_blog=Blog.find(params[:id])

	end
end

app/views/blogs/index.html.erb
<% provide(:title,'Media') %>
<div class="media-page">
	<div class="tabbable tab-set">
		<ul class= "nav nav-tabs">
			<li class="news-link" ><a href="#news-tab" data-toggle="tab">Past Articles</a></li>
			<li class="blogs-link active"><a href="#blog-tab" data-toggle="tab">Past Blogs</a></li>
		</ul>

		<div class="news-archive">
			<div class="tab-content">
				<div id="news-tab" class="tab-pane news-link">
					<h3 class="center"> Past Articles</h3>
					<% @archive_news.each do |article| %>
						<p><%= link_to(article.title, article.link, target: "blank") %> <br />
						<%= article.source %>--<%= article.created_at.strftime("%b %d, %Y") %></p>
					<% end %>
				</div>
				<div id="blog-tab" class="tab-pane active">
					<h3 class="center"> All Blogs</h3>
					<% @blogs.each do |blog| %>
						<p class="indent"><%= link_to(blog.title, blogs_path(blog)) %> - <%= blog.created_at.strftime("%b %d, %Y") %></p>
						<br />
					<% end %>
				</div>
			</div>
		</div>

	</div>
</div>
<script type="text/javascript">

</script>

app/views/blogs/show.html.erb
<%= provide(:title, "Message from Tim") %>
<div class="full-blog">
	<h5 class="center"><%= link_to "Blog Archives", mediablog_path %>
	<h4 class="center"><%= @full_blog.title %> - <%= @full_blog.created_at.strftime("%b %d, %Y") %></h4>
	<div class="tagline center"><%= @full_blog.tagline %></div>
	<p class="content"><%= simple_format @full_blog.content %></p>
</div>