config/routes.rb
TimOcchipinti::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :contributions, only: [:new, :create, :check]
  resources :blogs, only: [:show, :index]
  resources :news_articles, :only => :index

  resources :sessions, only: [:new, :create, :destroy]
  resources :guests, only: [:new, :create]
  resources :galleries, :has_many => :photos
  resources :photos

  root to:'pages#home'

  match '/about_tim',  	            to: 'pages#about_tim'
  match '/vision',                  to: 'pages#vision'
  match '/contribute',              to: 'contributions#new'
  match '/contribute/check',        to: 'contributions#check'
  match '/media',                   to: 'pages#media'
  match '/mediablog',               to: 'pages#media'
  match '/status_reports',          to: 'pages#status_reports'
  match '/contact',		              to: 'contact_us/contacts#new'
  match '/admin',                   to: 'pages#admin'
  match '/signin',                  to: 'sessions#new'
  match '/signout',                 to: 'sessions#destroy', via: :delete




end

app/models/contribution.rb
class Contribution < ActiveRecord::Base
  attr_accessor :card_number, :card_verification
  attr_accessible :card_number, :card_verification, :legal_notice, :address1, :address2, :amount, :card_expires_on, :card_type, :city, :email, :employer_address1, :employer_address2, :employer_city, :employer_name, :employer_state, :employer_zip, :name, :occupation, :state, :zip, :first_name, :last_name
  attr_writer :current_step
  validates_presence_of :name, :address1, :city, :state, :zip, :if => :personal?
  validates_format_of :zip, :with => %r{\d{5}(-\d{4})?}, :message => "should be 12345 or 12345-1234"
  validates_presence_of :occupation, :employer_name, :employer_address1, :employer_city, :employer_state, :employer_zip, :if => :employer?
  validates_presence_of :legal_notice, :if => :legal_notice?

  def current_step
  	@current_step || steps.first
  end

  def steps
  	%w[personal employer legal_notice]
  end

  def next_step
  	self.current_step = steps[steps.index(current_step)+1]
  end
  def previous_step
  	self.current_step = steps[steps.index(current_step)-1]
  end
  def first_step?
  	current_step == steps.first
  end
  def last_step?
  	current_step == steps.last
  end

  def save_step?
    current_step == steps.third
  end

   def personal?
    current_step == "personal"
  end

  def employer?
  	current_step == "employer"
  end

  def legal_notice?
    current_step == "legal_notice"
  end

def all_valid?
  steps.all? do |step|
    self.current_step = step
    valid?
  end
end

  
end

app/controllers/contributions_controller.rb
class ContributionsController < ApplicationController
  # GET /contributions
  # GET /contributions.json

  def new
    session[:contribution_params] ||= {}
    @contribution = Contribution.new(session[:contribution_params])
    @contribution.current_step = session[:contribution_step]
  end



 def create
    session[:contribution_params].deep_merge!(params[:contribution]) if params[:contribution]
    @contribution = Contribution.new(session[:contribution_params])
    @contribution.current_step = session[:contribution_step]
    if @contribution.valid?
      if params[:back_button]
        @contribution.previous_step
      elsif @contribution.last_step?
      @contribution.save if @contribution.all_valid?
            else
        @contribution.next_step
      end
      session[:contribution_step] = @contribution.current_step
    end
    if @contribution.new_record?
      render 'new'
    else
      session[:contribution_step] = session[:contribution_params] = nil
      redirect_to 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=M7WJB2AGSQZSE'
        Contributor.contributor_information(@contribution).deliver
    end
  end


end

app/helpers/contributions_helper.rb
module ContributionsHelper

	def current_step
		@current_step || steps.first
	end
	
	def steps
		%w[personal employer payment]
	end
end

app/views/contributions/_check_contribution.html.erb
<div id="mail-to">
	<p>Please make checks payable to:  <span class="large-font"><b>Occhipinti for Council</b></span></p>
	<br>
	<p class="large-font underline"><b>Mail to:</b></p>
	<p class="closer-lines">
	Occhipinti for Council<br>
	79 Monroe St <br>
	Apt 2RN<br>
	Hoboken NJ 07030<br>
	</p>
	<br>
	<p><br><b>
	***Please include the following contributor information with your contribution***</b><br>
	Name<br>
	Address<br>
	Email<br>
	Occupation(If a student or retired please enter home address below.)<br>
	Employer<br>
	Employer Address<br>
	</p>
</div>

app/views/contributions/_contribute_links.html.erb
<div class="contribute-links"><p><%= link_to "Paypal/Credit Card", contribute_path  %>|<%= link_to "Check", contribute_check_path %></p></div>

app/views/contributions/_electronic_contribution.html.erb
<div class="contribute">
	<%= semantic_form_for @contribution do |f| %>
	 	<%= render 'shared/error_messages', object: f.object %>
	 	<%= render "#{@contribution.current_step}_step", :f => f %>
  	    <%= f.actions do %>
	      	<%= f.submit "Back", :name => "back_button" unless @contribution.first_step? || @contribution.last_step?%>
	      	<%= f.action :submit, :label => "Continue"  unless @contribution.last_step? %>
	      	<% if @contribution.last_step? %>
	      		<div id="donate-button">
	      		<form action="https://www.paypal.com/cgi-bin/webscr" method="post">
					<input type="hidden" name="cmd" value="_s-xclick">
					<input type="hidden" name="hosted_button_id" value="M7WJB2AGSQZSE">
					<input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
					<img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
				</form>
			</div>
			<% end %>
    	<% end %>
	<% end %>
</div>

app/views/contributions/_employer_step.html.erb
<h2>Employment Information</h2>
	<%= f.input :employer_name, :label => "Employer" %>
	<%= f.input :occupation, :label => "Occupation", :hint => "If not employed, enter home address below." %>
	<%= f.input :employer_address1, :label => "Address" %>
    <div class="city-state-zip hidden-phone">
	 	<%= f.input :employer_city, :label => "City/State/Zip", :wrapper_html => { :class => 'fl' } %>
		<%= f.select :employer_state, options_for_select(us_states), :wrapper_html => { :class => 'fl' }%>
		<%= f.input :employer_zip, :label => false, :wrapper_html => { :class => 'fl' }%>
</div>
<div class="visible-phone">
  <%= f.input :employer_city, :label => "City", :wrapper_html => { :class => 'fl' } %>
    <%= f.select :employer_state, options_for_select(us_states), :wrapper_html => { :class => 'fl' }%>
    <%= f.input :employer_zip, :label => "Zip", :wrapper_html => { :class => 'fl' }%>
</div>

app/views/contributions/_form.html.erb
<%= semantic_form_for @contribution do |f| %>
  <%= f.inputs do %>
    <%= f.input :name %>
    <%= f.input :address1 %>
    <%= f.input :city %>
    <%= f.input :state %>
    <%= f.input :zip %>
    <%= f.input :email %>
    <%= f.input :occupation %>
    <%= f.input :employer_name %>
    <%= f.input :employer_address1 %>
    <%= f.input :employer_address2 %>
    <%= f.input :employer_city %>
    <%= f.input :employer_state %>
    <%= f.input :employer_zip %>
    <%= f.input :amount %>
    <%= f.input :card_type %>
    <%= f.input :card_expires_on %>
  <% end %>

  <%= f.actions do %>
    <%= f.action :submit, :as => :input %>
  <% end %>
<% end %>

app/views/contributions/_intro.html.erb
<div id="mail-to">
<p>Please make checks payable to:  <b>Occhipinti for Council</b></p>
<br>
<p><b>Mail to:</b></p>
<p class="closer-lines">
Occhipinti for Council<br>
422 Monroe St APT 1R<br>
Hoboken, NJ 07030
</p>
<br>
<p class="closer-lines">
***Please include the following contributor information with your contribution or use our secure on-line contribution feature below.***
</p>
</div>

app/views/contributions/_legal_compliance.html.erb
<div class="legal-compliance">
	<b class="underline">Legal Compliance</b>
	<p>
		1. This contribution is made from my own personal funds and is not made from the general treasury funds of a corporation, labor organization, or national bank.
	</p>
	<p>
		2. This contribution is made on a personal credit card and not a corporate credit card or the credit card of another person.
	</p>
	<p>
		3. I understand that I may not contribute in excess of $2,600 per candidate per election.
	</p>
	<p>
		4. I certify the information provided is true and accurate to the best of my knowledge.
	</p>
</div>

app/views/contributions/_legal_notice_step.html.erb
<h2>Legal Notice</h2>
<%= render :partial => 'legal_compliance' %>
<%= f.input :legal_notice, :label => "I have read and understand the above terms." %>

app/views/contributions/_payment_step.html.erb
<h2>Payment Info</h2>
<p>
 	<%= f.label :card_type, "Credit Card:  " %>
    <%= f.select :card_type, [["Visa", "visa"], ["MasterCard", "master"], ["Discover", "discover"], ["American Express", "american_express"]] %>
</p>

app/views/contributions/_personal_step.html.erb
<h2>Personal Information</h2>
    <%= f.input :name %>
    <%= f.input :email %>
    <%= f.input :address1, :label => "Address" %>
    <%= f.input :address2, :label => "Apt/Floor/Suite" %>
    <div class="city-state-zip hidden-phone">
	 	<%= f.input :city, :label => "City/State/Zip", :wrapper_html => { :class => 'fl' } %>
		<%= f.select :state, options_for_select(us_states), :name => "state", :wrapper_html => { :class => 'fl' }%>
		<%= f.input :zip, :label => false, :wrapper_html => { :class => 'fl' }%>
</div>

app/views/contributions/check.html.erb
<%= provide(:title, 'Contribute') %>
<%= render :partial => 'contribute_links' %>
<div class="contribute">
	<div id="mail-to">
	<p>Please make checks payable to:  <span class="large-font"><b>Occhipinti for Council</b></span></p>
	<br>
	<p class="large-font underline"><b>Mail to:</b></p>
	<p class="closer-lines">
	Occhipinti for Council<br>
	79 Monroe St <br>
	Apt 2RN<br>
	Hoboken NJ 07030<br>
	</p>
	<br>
	<p><br><b>
	***Please include the following contributor information with your contribution***</b><br>
	Name<br>
	Address<br>
	Email<br>
	Occupation(If a student or retired please enter home address below.)<br>
	Employer<br>
	Employer Address<br>
	</p>

	</div>
</div>

app/views/contributions/edit.html.erb
<h1>Editing contribution</h1>

<%= render 'form' %>

<%= link_to 'Show', @contribution %> |
<%= link_to 'Back', contributions_path %>

app/views/contributions/index.html.erb
<h1>Listing contributions</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Address1</th>
    <th>City</th>
    <th>State</th>
    <th>Zip</th>
    <th>Email</th>
    <th>Occupation</th>
    <th>Employer name</th>
    <th>Employer address1</th>
    <th>Employer address2</th>
    <th>Employer city</th>
    <th>Employer state</th>
    <th>Employer zip</th>
    <th>Amount</th>
    <th>Card type</th>
    <th>Card expires on</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @contributions.each do |contribution| %>
  <tr>
    <td><%= contribution.name %></td>
    <td><%= contribution.address1 %></td>
    <td><%= contribution.city %></td>
    <td><%= contribution.state %></td>
    <td><%= contribution.zip %></td>
    <td><%= contribution.email %></td>
    <td><%= contribution.occupation %></td>
    <td><%= contribution.employer_name %></td>
    <td><%= contribution.employer_address1 %></td>
    <td><%= contribution.employer_address2 %></td>
    <td><%= contribution.employer_city %></td>
    <td><%= contribution.employer_state %></td>
    <td><%= contribution.employer_zip %></td>
    <td><%= contribution.amount %></td>
    <td><%= contribution.card_type %></td>
    <td><%= contribution.card_expires_on %></td>
    <td><%= link_to 'Show', contribution %></td>
    <td><%= link_to 'Edit', edit_contribution_path(contribution) %></td>
    <td><%= link_to 'Destroy', contribution, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Contribution', new_contribution_path %>

app/views/contributions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @contribution.name %>
</p>

<p>
  <b>Address1:</b>
  <%= @contribution.address1 %>
</p>

<p>
  <b>City:</b>
  <%= @contribution.city %>
</p>

<p>
  <b>State:</b>
  <%= @contribution.state %>
</p>

<p>
  <b>Zip:</b>
  <%= @contribution.zip %>
</p>

<p>
  <b>Email:</b>
  <%= @contribution.email %>
</p>

<p>
  <b>Occupation:</b>
  <%= @contribution.occupation %>
</p>

<p>
  <b>Employer name:</b>
  <%= @contribution.employer_name %>
</p>

<p>
  <b>Employer address1:</b>
  <%= @contribution.employer_address1 %>
</p>

<p>
  <b>Employer address2:</b>
  <%= @contribution.employer_address2 %>
</p>

<p>
  <b>Employer city:</b>
  <%= @contribution.employer_city %>
</p>

<p>
  <b>Employer state:</b>
  <%= @contribution.employer_state %>
</p>

<p>
  <b>Employer zip:</b>
  <%= @contribution.employer_zip %>
</p>

<p>
  <b>Amount:</b>
  <%= @contribution.amount %>
</p>

<p>
  <b>Card type:</b>
  <%= @contribution.card_type %>
</p>

<p>
  <b>Card expires on:</b>
  <%= @contribution.card_expires_on %>
</p>


<%= link_to 'Edit', edit_contribution_path(@contribution) %> |
<%= link_to 'Back', contributions_path %>