config/routes.rb
TimOcchipinti::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :contributions, only: [:new, :create, :check]
  resources :blogs, only: [:show, :index]
  resources :news_articles, :only => :index

  resources :sessions, only: [:new, :create, :destroy]
  resources :guests, only: [:new, :create]
  resources :galleries, :has_many => :photos
  resources :photos

  root to:'pages#home'

  match '/about_tim',  	            to: 'pages#about_tim'
  match '/vision',                  to: 'pages#vision'
  match '/contribute',              to: 'contributions#new'
  match '/contribute/check',        to: 'contributions#check'
  match '/media',                   to: 'pages#media'
  match '/mediablog',               to: 'pages#media'
  match '/status_reports',          to: 'pages#status_reports'
  match '/contact',		              to: 'contact_us/contacts#new'
  match '/admin',                   to: 'pages#admin'
  match '/signin',                  to: 'sessions#new'
  match '/signout',                 to: 'sessions#destroy', via: :delete




end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :description, :image, :photo_id, :gallery_id, :remote_image_url
  belongs_to :gallery
  mount_uploader :image, ImageUploader

  default_scope order: 'photos.created_at DESC'

  validates :gallery_id, presence: true

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  # def new
  #   @photo = Photo.new(:gallery_id => params[:gallery_id])
  # end

  # def create
  #   @photo = Photo.new(params[:photo])
  #   if @photo.save
  #     flash[:notice] = "Successfully created photo."
  #     redirect_to @photo.gallery
  #   else
  #     render :action => 'new'
  #   end
  # end

  # def edit
  #   @photo = Photo.find(params[:id])
  # end

  # def update
  #   @photo = Photo.find(params[:id])
  #   if @photo.update_attributes(params[:photo])
  #     flash[:notice] = "Successfully updated photo."
  #     redirect_to @photo.gallery
  #   else
  #     render :action => 'edit'
  #   end
  # end


  # def destroy
  #   @photos = Photo.find(params[:id])
  #   @photos.destroy
  #   flash[:notice] = "Successfully destroyed photo."
  #   redirect_to @photos.gallery
  # end

end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.erb
<%= form_for @photo, :html => {:multipart => true} do |f| %>
  <%= f.error_messages %>
  <%= f.hidden_field :gallery_id %>
  <p>
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </p>
  <p>
    <%= f.file_field :image %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/photos/_photo.html.erb
<li>
 %= link_to image_tag(photo.image), gallery_photos_path(@gallery) %>
</li>

app/views/photos/edit.html.erb
<%= provide(:title, 'Edit Photo') %>
<p class="center"><%= link_to "Back to Gallery", @photo.gallery %></p>
<p class="center edit-image"><%= image_tag(@photo.image_url.to_s) %></p>
<p class=center>
    <%= link_to "DELETE Photo", @photo, method: :delete, data: { confirm: "You sure?"} %>
</p>
<div class="gallery-form">
	<%= semantic_form_for @photo do |f| %>
	    <p class= "descripton">
			<%= f.input :description, :as => :text, :label => t('.description (optional):  ') %>
	   	</p>      
	    <p class="center">
		    <%= f.submit "Update Description", class: "btn btn-large btn-primary" %>
		</p>
	<% end %>
</div>

app/views/photos/index.html.erb
<div id="gallery-page">
	<h5><%= link_to "Back to Gallery Index", galleries_path %></h5>

				<%= @photo%>
	
	
</div>

app/views/photos/new.html.erb
<%= provide(:title, "Add Photo to #{@photo.gallery.name}") %>
<p class="center"><%= link_to "Back to #{@photo.gallery.name}", gallery_path(@photo.gallery.id)%></p>
<div class="gallery-form">
  <%= semantic_form_for @photo, :html => {:multipart => true} do |f| %>
 	  <%= render 'shared/error_messages', object: f.object %>
    <%= f.hidden_field :gallery_id %>
    <h5>Basic Info</h5>
    <p>
      <%= f.label :image, "Upload Image:  " %>
      <%= f.file_field :image %>
    </p>
    <p>
      <%= f.label :remote_image_url, "or image URL:" %>
      <%= f.text_field :remote_image_url %>
    </p>
    <p class= "descripton">
			<%= f.input :description, :as => :text, :label => t('.description (optional):  ') %>
    </p>
    <p class ="center">
      <%= f.submit "Add Photo", class: "btn btn-large btn-primary" %>
    </p>
  <% end %>
</div>
</div>