config/routes.rb
TimOcchipinti::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :contributions, only: [:new, :create, :check]
  resources :blogs, only: [:show, :index]
  resources :news_articles, :only => :index

  resources :sessions, only: [:new, :create, :destroy]
  resources :guests, only: [:new, :create]
  resources :galleries, :has_many => :photos
  resources :photos

  root to:'pages#home'

  match '/about_tim',  	            to: 'pages#about_tim'
  match '/vision',                  to: 'pages#vision'
  match '/contribute',              to: 'contributions#new'
  match '/contribute/check',        to: 'contributions#check'
  match '/media',                   to: 'pages#media'
  match '/mediablog',               to: 'pages#media'
  match '/status_reports',          to: 'pages#status_reports'
  match '/contact',		              to: 'contact_us/contacts#new'
  match '/admin',                   to: 'pages#admin'
  match '/signin',                  to: 'sessions#new'
  match '/signout',                 to: 'sessions#destroy', via: :delete




end

app/views/layouts/_cell_phone_footer.html.erb
<footer class="visible-phone">
  <div class="row-fluid">
    <div class="navbar">
    <div class="navbar-inner">
      <div class="container">
         <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse2">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
         <span class="brand">Government Links</span>
        <div class="nav-collapse2 nav-collapse">
          <ul class="nav">
            <li><%= link_to("City of Hoboken", 'http://www.hobokennj.org/', :target => 'blank')%></li>
        <li><%= link_to("Hoboken Housing Authority", 'http://www.myhhanj.com/', target: 'blank') %></li>
        <li><%= link_to("Hoboken Police Department", 'http://www.hobokenpd.com/', target: 'blank') %></li>
        <li><%= link_to("Hudson County", 'http://www.hudsoncountynj.org/', target: 'blank') %></li>
        <li><%= link_to("Congressman Albio Sires", 'http://sires.house.gov/', target: 'blank') %></li>
        <li><%= link_to("Senator Menendez", 'http://www.menendez.senate.gov/', target: 'blank') %></li>
        <li><%= link_to("Senator Lautenberg", 'http://www.lautenberg.senate.gov/', target: 'blank') %></li>
        <li><%= link_to("State of NJ", 'http://nj.gov/', target: 'blank') %></li>
        <!-- <h5>News Links</h5>
        <li><%= link_to("Hoboken Reporter", 'http://hudsonreporter.com/pages/hoboken', target: "blank") %></li>
        <li><%= link_to("Jersey Journal", 'http://www.nj.com/hobokennow/', target: 'blank') %></li>
        <li><%= link_to("Hoboken Patch", 'http://hoboken.patch.com', target: 'blank') %></li>
        <li><%= link_to("Hoboken 411", 'http://hoboken411.com', target: 'blank') %></li>    -->
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="row-fluid">
    <div class="navbar">
    <div class="navbar-inner">
      <div class="container">
         <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse3">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
         <span class="brand">News Links</span>
        <div class="nav-collapse3 nav-collapse">
          <ul class="nav">
            <li><%= link_to("Hoboken Reporter", 'http://hudsonreporter.com/pages/hoboken', target: "blank") %></li>
            <li><%= link_to("Jersey Journal", 'http://www.nj.com/hobokennow/', target: 'blank') %></li>
            <li><%= link_to("Hoboken Patch", 'http://hoboken.patch.com', target: 'blank') %></li>
            <li><%= link_to("Hoboken 411", 'http://hoboken411.com', target: 'blank') %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
 <div class="row-fluid">
    <div class="navbar">
    <div class="navbar-inner">
      <div class="container">
         <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse4">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
         <span class="brand">Emergency Services</div>
        <div class="nav-collapse4 nav-collapse">
          <ul class="nav">
            <li><%= link_to("Hoboken Snow Routes", 'http://www.hobokennj.org/emergency-snow-routes/', target: 'blank') %></li>
            <li><%= link_to("Hoboken Flood Maps", 'http://www.hobokennj.org/departments/environmental-services/storm-flood-zones/', target: 'blank') %></li>
            <li><%= mail_to('complaints@hudsonregionalhealth.org',"Hudson County Health Complaints") %>-(201)223-1133</li>
            <li><%= link_to("Hudson County Mosquito Control", 'http://www.hudsonregional.org/mosquito/', target: 'blank') %><%= mail_to('gwilliams@hudsonregionalhealth.org', '-email') %></li>
            <li>Animal Control – Call Hoboken PD-(201)420-2100</li>
            <li>Hoboken Housing Authority PD–(201)222-7621</li>
          </ul>
        </div>
      </div>
    </div>
  </div>    
 <div class="row-fluid">
    <div class="navbar">
    <div class="navbar-inner">
      <div class="container">
         <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse5">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
          <span class="brand">Service Organizations</span>
          <div class="nav-collapse5 nav-collapse">
            <ul class="nav">
              <li><%= link_to("Hoboken Volunteers", ' http://www.hobokenvolunteers.com/', target: 'blank') %></li>
          <li><%= link_to("Hoboken Chamber of Commerce", 'http://hobokenchamber.com/', target: 'blank') %></li>
          <li><%= link_to("Hoboken Rotary Club", 'http://www.hobokenrotary.org/', target: 'blank') %></li>
          <li><%= link_to("Hoboken Shelter", 'http://www.hobokenshelter.org', target: 'blank') %></li>
          <li><%= link_to("Hoboken Museum", 'http://www.hobokenmuseum.org', target: 'blank') %></li>
          <li><%= link_to("Hoboken Volunteer Ambulance Corps.", 'http://hobokenems.com', target: 'blank') %></li>
          <li><%= link_to("Habitat For Humanity of Hudson Count", 'http://habitathudsoncounty.org/', target: 'blank') %></li>
          <li><%= link_to("HOPES CAP, Inc Community Action Partnerships", 'http://www.hopes.org', target: 'blank') %></li>
          <li><%= link_to("Boys & Girls Clubs of Hudson County", 'http://www.bgchc.org') %></li>
          <li><%= link_to("Party With Purpose", 'http://www.partywithpurpose.org', target: 'blank') %></li>
          <li><%= link_to("The Jubilee Center", 'http://jubileecenterhoboken.org', target: 'blank') %></li>
          <li><%= link_to("TRUE Mentors", 'http://www.truementors.org', target: 'blank') %></li>
         </ul>
        </div>
      </div>
    </div>
  </div>    
</footer>

app/views/layouts/_contribute_button.html.erb
	<div id="contribute-button">
		<%= link_to image_tag('contribute.jpeg'), contribute_path %>
	</div>
</div>

app/views/layouts/_footer.html.erb
<footer class="fixed-bottom hidden-phone">
  <div class="row-fluid">
    <div class="span4" id="government-links">
      <ul><h5>Government Links</h5>
        <li> <%= link_to'http://www.hobokennj.org/docs/clerk/Fourth_Ward_4.pdf', target: "blank" do %>
          4<sup>th</sup>&nbsp;Ward&nbsp;Map
          <% end %>
        </li>
       <li><%= link_to("City of Hoboken", 'http://www.hobokennj.org/', :target => 'blank')%></li>
        <li><%= link_to("Hoboken Housing Authority", 'http://www.myhhanj.com/', target: 'blank') %></li>
        <li><%= link_to("Hoboken Police Department", 'http://www.hobokenpd.com/', target: 'blank') %></li>
        <li><%= link_to("Hudson County", 'http://www.hudsoncountynj.org/', target: 'blank') %></li>
        <li><%= link_to("Congressman Albio Sires", 'http://sires.house.gov/', target: 'blank') %></li>
        <li><%= link_to("Senator Menendez", 'http://www.menendez.senate.gov/', target: 'blank') %></li>
        <li><%= link_to("Senator Lautenberg", 'http://www.lautenberg.senate.gov/', target: 'blank') %></li>
        <li><%= link_to("State of NJ", 'http://nj.gov/', target: 'blank') %></li>
        <h5>News Links</h5>
        <li><%= link_to("Hoboken Reporter", 'http://hudsonreporter.com/pages/hoboken', target: "blank") %></li>
        <li><%= link_to("Jersey Journal", 'http://www.nj.com/hobokennow/', target: 'blank') %></li>
        <li><%= link_to("Hoboken Patch", 'http://hoboken.patch.com', target: 'blank') %></li>
        <li><%= link_to("Hoboken 411", 'http://hoboken411.com', target: 'blank') %></li>
      </ul>
    </div>
    <div class="span4" id="emergency-links">
      <ul><h5>Emergency Services</h5>
        <li><%= link_to("Hoboken Snow Routes", 'http://www.hobokennj.org/emergency-snow-routes/', target: 'blank') %></li>
        <li><%= link_to("Hoboken Flood Maps", 'http://www.hobokennj.org/departments/environmental-services/storm-flood-zones/', target: 'blank') %></li>
        <li><%= mail_to('complaints@hudsonregionalhealth.org',"Hudson County Health Complaints") %>-(201)223-1133</li>
        <li><%= link_to("Hudson County Mosquito Control", 'http://www.hudsonregional.org/mosquito/', target: 'blank') %><%= mail_to('gwilliams@hudsonregionalhealth.org', '-email') %></li>
        <li>Animal Control – Call Hoboken PD-(201)420-2100</li>
        <li>Hoboken Housing Authority PD–(201)222-7621</li>
      </ul>
    </div>
    <div class="span4" id="service-organizations">
      <ul><h5>Service Organizations</h5>
        <li><%= link_to("Hoboken Volunteers", ' http://www.hobokenvolunteers.com/', target: 'blank') %></li>
        <li><%= link_to("Hoboken Chamber of Commerce", 'http://hobokenchamber.com/', target: 'blank') %></li>
        <li><%= link_to("Hoboken Rotary Club", 'http://www.hobokenrotary.org/', target: 'blank') %></li>
        <li><%= link_to("Hoboken Shelter", 'http://www.hobokenshelter.org', target: 'blank') %></li>
        <li><%= link_to("Hoboken Museum", 'http://www.hobokenmuseum.org', target: 'blank') %></li>
        <li><%= link_to("Hoboken Volunteer Ambulance Corps.", 'http://hobokenems.com', target: 'blank') %></li>
        <li><%= link_to("Habitat For Humanity of Hudson Count", 'http://habitathudsoncounty.org/', target: 'blank') %></li>
        <li><%= link_to("HOPES CAP, Inc Community Action Partnerships", 'http://www.hopes.org', target: 'blank') %></li>
        <li><%= link_to("Boys & Girls Clubs of Hudson County", 'http://www.bgchc.org') %></li>
        <li><%= link_to("Party With Purpose", 'http://www.partywithpurpose.org', target: 'blank') %></li>
        <li><%= link_to("The Jubilee Center", 'http://jubileecenterhoboken.org', target: 'blank') %></li>
        <li><%= link_to("TRUE Mentors", 'http://www.truementors.org', target: 'blank') %></li>
       </ul>
    </div>
  </div>
  <div class="row-fluid">
    <div class="span12">
    <ul id="bottom-line">
      <li> Paid for by Occhipinti for Council 79 Monroe Street Apt. 2RN Hoboken, NJ </li>
      <% if signed_in? %>
        <%= link_to "Sign Out", destroy_admin_user_session_path, :target => "'blank'" %>
        
      <% else %>
          <li><%= link_to "Admin Tools", admin_path, target: "'blank'" %></li>
      <% end %>
    <li><%= mail_to("sethb78@gmail.com", "Site by Seth B. Altshuler")%></li>
  </ul>
  </div>
  </div>
</footer>


<%= render 'layouts/cell_phone_footer' %>

app/views/layouts/_intouch.html.erb
<div id="in-touch">
	<h4 class="text-center">STAY IN TOUCH</h4>
  <div class="row-fluid">
 
 <ul class="inline text-center">
  <li class="facebook-button">
    <%= link_to('https://www.facebook.com/tim.occhipinti') do %>
      <i class="icon-facebook"></i>
    <% end %>
  </li>

  <li class="twitter-button">
    <%= link_to("https://twitter.com/TimOcchipinti") do %>
      <i class="icon-twitter"></i>
    <% end %>
  </li> 

  <li class="youtube-button">
    <%= link_to('http://www.youtube.com/user/occhipinti4hoboken?feature=watch') do %>
      <i class="icon-youtube"></i>
    <% end %>
  </li>
 <li class="email-button">
<% mail_content = capture do %>
          <i class="icon-envelope-alt "></i>
<% end %>

<%= mail_to ("tim.occhipinti@gmail.com") , mail_content %>
        </li>


      </ul>
  </div>
</div>

app/views/layouts/_main_image.html.erb
<%= link_to image_tag('tim_banner.png', alt: "Tim Occhipinti - Representing The 4th Ward In Hoboken", class: "banner_image"), root_path %>

app/views/layouts/_navigation-bar.html.erb
<div class="navigation-bar">
	<div class="navbar">
		<div class="navbar-inner">
			<div class="container">
				 <a class="btn btn-navbar visible-phone" data-toggle="collapse" data-target=".nav-collapse_top">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
										<span class="icon-bar"></span>

				</a>
				<div class="visible-tablet">
					<%= render 'layouts/navigation_tabs' %>
				</div>
				<div class="nav-collapse_top nav-collapse">
					<%= render 'layouts/navigation_tabs' %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/layouts/_navigation_tabs.html.erb
<ul class="nav">
			    	<li> <%= link_to "About Tim", about_tim_path %></li>
			    	<li><%= link_to "Contributions",contribute_path %></li>
	<!-- 				 <li> <%= link_to "Status Reports", status_reports_path %></li> -->
					 	<li> <%= link_to "In The News", media_path %></li>
					 	<li class="hidden-phone photo_galleries_nav"> <%= link_to "Photo Galleries", galleries_path %></li>
					 	<li> <%= link_to "Contact", contact_path %></li>	
  
					</ul>

app/views/layouts/_petition.html.erb
<form id="overlay_form" style="display:none">
	<div id="blanket"></div>
  <h2 class="center">Acquire Property at 1st and Jackson Streets for Public Open Space</h2>
  <div id ="petition_text">
    <p class="bold">
      Hoboken needs leaders committed to creating safe places for our children to play and for all our families to enjoy.
    </p>
    <p>
      Right now, we have the chance to make a real difference along these lines. And that's why I hope you'll click this link below and sign our petition advocating for new open space at 1st and Jackson Streets.
    </p>
    <p>
      We've already collected almost 300 signatures in a little over one week. <span class="bold"><%= link_to "On March 20th, we'll present this petition", "http://www.change.org/petitions/city-of-hoboken-acquire-property-at-1st-and-jackson-streets-for-public-open-space-2", target: "blank" %></span> to Mayor Zimmer and the City Council at that night's council meeting. I hope you'll join us that evening to let your voice be heard during the Public Comments section at the beginning of the meeting.
    </p>
    <p>
      I also want to clarify that advocating for new open space at these lots in no way infringes upon the goal for a large continuous park in the 4th Ward. These lots would be in addition to the SW6 Plan
    </p>
    <p>
      These two lots can be purchased now in addition to building the much-needed 6-acre park. <span class="bold">By purchasing and turning them into green open space for the few thousand people in the SW part of Hoboken, it in no way minimizes or undermines the urgent need for a 6 acre park in that area.</span> The $3 million grant from the Hudson County Trust Fund dedicated to open space in SW Hoboken is due to run out this summer. It was extended last summer by request of the Zimmer Administration.
    </p>
    <p>
      <span class="bold">To date, the Zimmer Administration has not spent a single dollar on acquiring new open space in the 4th Ward.</span> They have two funding mechanisms, the $3 million Hudson County Grant and the $20 million bond authorization by the City Council approved in the spring of 2011. For years, residents have been taxed by both Hudson County and the City for open space with no new parks added to our neighborhoods. 
    </p>
    <p>
      In our urban landscape, we need as much open space as possible. Especially here in Southwest Hoboken. Let's begin the process of acquiring the vacant lot and Nardine's at 1st and Jackson Street as soon as possible.
      </p>
    </div>
  <ul>
  	<li class="btn btn-medium btn-primary"><%= link_to("Sign Petition", "http://www.change.org/petitions/city-of-hoboken-acquire-property-at-1st-and-jackson-streets-for-public-open-space-2", target: 'blank') %></li>
    <li id="close"><%= link_to("close window", root_path) %></li>
  </ul>
</form>

app/views/layouts/_scripts.html.erb
<% if Rails.env == "production" %>
	<script type="text/javascript">

	  var _gaq = _gaq || [];
	  _gaq.push(['_setAccount', 'UA-38171296-1']);
	  _gaq.push(['_trackPageview']);

	  (function() {
	    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
	    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
	    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	  })();

	</script>
<% end %>

app/views/layouts/_shim.html.erb
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->

app/views/layouts/_title.html.erb
<div class="title-box">
	<h1><span></span>Tim Occhipinti</h1>
	<!--<h4>Representing The 4th Ward In Hoboken, NJ</h4>-->
</div>	

app/views/layouts/_topline.html.erb
<div id="mailing-list">
<div class="row-fluid">
  <div class="span12">
<h5 class="text-center">Sign Up For Email Alerts:  </h5>
  </div>
</div>
<div class="row-fluid">
<div class="span12 text-center">
    <form name="ccoptin" action="http://visitor.constantcontact.com/d.jsp" method="post" target="blank">
  <input type="hidden" name="m" value="1103157500718">
    <input type="hidden" name="p" value="oi">
    <input type="text" name="ea" placeholder="Your Email Address">
    <input type="submit" value="Sign Up" class="btn">
</form>
</div>
</div>
</div>

app/views/layouts/_twitter.html.erb
<a class="twitter-timeline"  href="https://twitter.com/TimOcchipinti"  data-widget-id="284398640125067265">Tweets by @TimOcchipinti</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

app/views/layouts/_voter_registration.html.erb
<div id="register_to_vote">
	<%= link_to image_tag('register_to_vote.jpg'), 'http://www.state.nj.us/state/elections/voting-information-voter-registration-forms.html', target: 'blank' %>
</div>
					